export interface MasteryLevel {
  id: number // 41–50
  title: string
  concept: string
  description: string
  goal: string
  wordLimit: number
  criteria: string[]
  max_xp: number
  keyRule: string
}

export const MASTERY_LEVELS: MasteryLevel[] = [
  {
    id: 41,
    title: 'The Synthesis',
    concept: 'Combined Skills',
    description: 'All four pillars working as one.',
    goal: 'Write a clear prompt under 20 words that asks for a structured list with exactly 3 items',
    wordLimit: 20,
    criteria: [
      'Prompt is clear and states the task unambiguously',
      'Explicitly requests a structured list',
      'Specifies exactly 3 items — no more, no fewer',
      'Stays within the 20-word limit',
    ],
    max_xp: 200,
    keyRule: 'All skills work together or not at all.',
  },
  {
    id: 42,
    title: 'The Analogy',
    concept: 'Clarity + Constraints',
    description: 'Simplify without sacrificing precision.',
    goal: 'In 25 words or less ask an AI to explain a complex topic simply using only an analogy',
    wordLimit: 25,
    criteria: [
      'Complex topic is specified clearly',
      'Explicitly requires an analogy as the explanation method',
      'Requests simple, accessible language',
      'Stays within 25 words',
    ],
    max_xp: 250,
    keyRule: 'Combine clarity and constraints for precision.',
  },
  {
    id: 43,
    title: 'The Self-Fixer',
    concept: 'Structure + Debug',
    description: 'Build a prompt that solves its own problems.',
    goal: 'Write a prompt that is specific, structured, and fixes its own ambiguity — all in under 30 words',
    wordLimit: 30,
    criteria: [
      'Prompt is highly specific — no vague terms',
      'Has a clear structural element (list, steps, or format)',
      'Anticipates and resolves at least one potential ambiguity',
      'Under 30 words',
    ],
    max_xp: 300,
    keyRule: 'Structure your way out of ambiguity.',
  },
  {
    id: 44,
    title: 'The Constrained Creator',
    concept: 'Constraints + Structure',
    description: 'Creativity thrives under exactly the right pressure.',
    goal: 'Ask for creative output with exactly 4 constraints and a clear format in under 35 words',
    wordLimit: 35,
    criteria: [
      'Creative output is requested',
      'Exactly 4 distinct constraints are present',
      'A clear output format is specified',
      'Under 35 words',
    ],
    max_xp: 350,
    keyRule: 'Debug before you send.',
  },
  {
    id: 45,
    title: 'The Controller',
    concept: 'All Four Pillars',
    description: 'Every variable under your command.',
    goal: 'Write a prompt that controls tone, length, audience, and format simultaneously in under 40 words',
    wordLimit: 40,
    criteria: [
      'Tone is explicitly specified',
      'Length constraint is stated',
      'Audience is defined',
      'Output format is required',
      'All four controls appear in under 40 words',
    ],
    max_xp: 400,
    keyRule: 'Control every variable.',
  },
  {
    id: 46,
    title: 'The Replicable',
    concept: 'Precision + Consistency',
    description: 'The best prompts produce the same result every time.',
    goal: 'Create a prompt that would get identical results every time it is run — under 45 words',
    wordLimit: 45,
    criteria: [
      'No ambiguous terms that could be interpreted differently each run',
      'All variables are explicitly defined',
      'Output format is deterministic',
      'Any subjective elements are removed or precisely constrained',
      'Under 45 words',
    ],
    max_xp: 450,
    keyRule: 'Consistency is the mark of mastery.',
  },
  {
    id: 47,
    title: 'The Full Stack',
    concept: 'Role + Task + Constraints + Format',
    description: 'Every element of a great prompt in one.',
    goal: 'Write a prompt combining a role, a task, constraints, and an output format in under 50 words',
    wordLimit: 50,
    criteria: [
      'A specific role is assigned to the AI',
      'The task is stated clearly and completely',
      'At least two constraints are included',
      'An output format is specified',
      'All four elements present in under 50 words',
    ],
    max_xp: 500,
    keyRule: 'The master prompt has no wasted words.',
  },
  {
    id: 48,
    title: 'The Operator',
    concept: 'Real-World Application',
    description: 'Master-level prompts solve real problems.',
    goal: 'Ask an AI to solve a real business problem with specific constraints and structured output in under 55 words',
    wordLimit: 55,
    criteria: [
      'A real, specific business problem is stated',
      'Constraints reflect genuine business requirements',
      'Output structure is defined and practical',
      'The prompt would be useful in a real professional context',
      'Under 55 words',
    ],
    max_xp: 550,
    keyRule: 'Real problems need real precision.',
  },
  {
    id: 49,
    title: 'The Template',
    concept: 'Reusability',
    description: 'One prompt, infinite applications.',
    goal: 'Write the most reusable prompt possible — one that works across 3 different contexts unchanged in under 60 words',
    wordLimit: 60,
    criteria: [
      'Prompt is abstract enough to work across multiple contexts',
      'No domain-specific terms that would limit applicability',
      'Structure is flexible but still directive',
      'Could plausibly serve 3 different use cases without modification',
      'Under 60 words',
    ],
    max_xp: 600,
    keyRule: 'Reusability is the highest form of efficiency.',
  },
  {
    id: 50,
    title: 'The Masterpiece',
    concept: 'Full Mastery',
    description: 'No constraints. No excuses. This is yours.',
    goal: 'Write the perfect prompt. No constraints on format or length. This is your masterpiece.',
    wordLimit: 100,
    criteria: [
      'Every element serves a purpose — nothing is wasted',
      'Clarity, constraints, structure, and debug skills all visible',
      'The prompt would produce an exceptional, specific output',
      'Demonstrates genuine mastery of prompt engineering',
      'Shows the player\'s unique voice and thinking style',
    ],
    max_xp: 600,
    keyRule: 'You are the prompt engineer.',
  },
]
